### ISSUE TITLE
su-exec: not found

### ISSUE THREAD

**Issue by KubaTrojan** [intel/observability-telegraf#1]
**Issue description:**
On Ubuntu 20.04, the container builds ok, but never starts up, spinning in a loop with

```
docker logs ee1a0a40f5bd
./entrypoint.sh: exec: line 11: su-exec: not found
./entrypoint.sh: exec: line 11: su-exec: not found
./entrypoint.sh: exec: line 11: su-exec: not found
./entrypoint.sh: exec: line 11: su-exec: not found
./entrypoint.sh: exec: line 11: su-exec: not found
./entrypoint.sh: exec: line 11: su-exec: not found
./entrypoint.sh: exec: line 11: su-exec: not found
...
```
**Roots of the issue:**
Telegraf alpine image has been updated, and now is using su-exec which is not installed in the base docker image.

The solution is to update docker image and stick to more specific Telegraf-alpine image version.

**Quick fix:**
To fix that, just edit Dockerfile and add su-exec dependency, here’s how it should look like:

```
RUN export PATH="/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin" && \
    apk update && \
    apk add --update --no-cache \
    bash=~5.1.4 \
    sudo=~1.9.7 \
    smartmontools=~7.2 \
    nvme-cli=~1.14 \
    rasdaemon=~0.6.7 \
    iptables=~1.8.7 \
    ipmitool=~1.8.18 \
    su-exec=~0.2-r1 \
    iputils=~20210202-r0 && \
    rm -rf /var/lib/apt/lists/*
```

**Comment by pduzinki** [comment]
Fixed with latest release [v1.1](https://github.com/intel/observability-telegraf/commit/f77fb01fd4d7bfb79900cc5e054e3d66882ae682)
